Us04 header
WildCodeSchool-2024-09/JS-Nantes-P2-Cookedup pull request #4
Opened 2024-11-14 15:26 UTC by Marcellin123

Header and footer available, please check it out

2024-11-15 09:09 UTC, GaeBolga approved these changes

2024-11-15 14:05 UTC, MrLootman requested changes

2024-11-15 14:05 UTC, MrLootman commented on client/src/assets/styles/Footer.css
> +}
Ce sélecteur ne doit pas être écrit dans un fichier aussi spécifique que `Footer.css`.
Il est nécessaire de voir avec tes collègues si un fichier `globals.css` a été créé, de façon à réunir tout le code général de l'application.
Il n'est pas une bonne pratique d'écrire le sélecteur `*` partout ou vous en avez besoin. Il faut l'écrire une fois et une seule.

2024-11-15 14:05 UTC, MrLootman commented on client/src/assets/styles/Footer.css
> +.Footer-box {
La convention de nommage des classes est le `kebab-case`.
Ici, il faut que la classe soit `footer-box`.

2024-11-15 14:05 UTC, MrLootman commented on client/src/assets/styles/Footer.css
> +.linkFooter {
Pareil ici. Le kebab-case est requis.

2024-11-15 14:05 UTC, MrLootman commented on client/src/assets/styles/header.css
> +}
A nouveau, le sélecteur `*`.

2024-11-15 14:05 UTC, MrLootman commented on client/src/assets/styles/header.css
Le fichier est nommé `header.css`. Or, il faudrait qu'il soit nommé `Header.css`.
Il faudra donc que tu fasses un `git mv header.css Header.css` pour le renommer.

2024-11-18 08:50 UTC, MrLootman approved these changes
👍

2024-11-18 08:51 UTC, merged