Feature/us09/recette card
WildCodeSchool-2024-09/JS-Nantes-P2-Cookedup pull request #5
Opened 2024-11-15 09:21 UTC by juliabelhassen

2024-11-15 14:18 UTC, MrLootman requested changes

2024-11-15 14:18 UTC, MrLootman commented on client/src/RecipeArray.tsx
> +
Du code mort. A supprimer avant intégration sur dev.

2024-11-15 14:18 UTC, MrLootman commented on client/src/assets/style/RecetteCard.css
> +
Problème : utilisation de style sur des balises non spécifiques.
En l'état, tout le body de l'application va être impacté par le display: grid, et toutes les balises main impactées par le code que tu as écris ici.

Il faut être plus spécifique, pour n'impacter que les composants sur lesquels tu travailles.

2024-11-15 14:18 UTC, MrLootman commented on client/src/assets/style/RecetteCard.css
> +img {
Problème encore : balise utilisée sans spécificité.

2024-11-18 08:51 UTC, MrLootman commented
Conflit avec RecetteCard à rectifier.

2024-11-18 08:54 UTC, MrLootman requested changes

2024-11-18 08:54 UTC, MrLootman commented on client/src/RecetteCard.tsx
Dans cette version que tu push, tu sembles avoir supprimé deux fichiers intitulés `RecetteCard`.
Cependant, il existe un fichier `RecetteCard.css` 🤔

2024-11-18 09:32 UTC, juliabelhassen commented on client/src/RecetteCard.tsx
Je supprime RecetteCard.tsx qui s'appelle désormais RecipeCard.tsx ? 
Le CSS correspond a la home page, je l'ai renomme en conséquence.

2024-11-20 09:22 UTC, closed without merging